web/yonomAIproject/post/urls.py
from django.urls import path
from . import views

app_name = "post"
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('made_by/', views.made_by, name='made_by'),
    path('video_content/', views.video_content, name='input_video'),
    path('home_number/', views.home_number, name='home_number'),
    path('main/', views.main, name='main'),
    path('error/', views.error, name='error'),
    path('insert_video/', views.insert_video, name='insert_video'),
    path('about2/', views.about2, name='about2'),
    path('about3/', views.about3, name='about3'),
    path('home_video/', views.home_video, name='home_video'),
    path('result/', views.result, name='result'),
]

web/yonomAIproject/yonomAIproject/urls.py
from django.contrib import admin
from django.urls import include, path
from post import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('about/', views.about, name='about'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/yonomAIproject/post/models.py
from django.db import models

# Create your models here.

class video_content(models.Model):
    video = models.FileField(upload_to='post', null=True)
    title = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.title


class mat(models.Model):
    title = models.CharField(max_length=50, null=True)
    mat = models.FileField(upload_to='mat', null=True)

    def __str__(self):
        return self.title

web/yonomAIproject/post/views.py
from django.shortcuts import render, redirect
from .models import video_content, mat
from scipy.io import loadmat
import matplotlib.pyplot as plt
import io
import urllib, base64
import cv2
import numpy as np
import os
import urllib, base64

################## 반복 실행 시키기 ####################
# import time 
# import threading 

# def thread_run():
#     print("test")

# rel = 0
# count = 5
# while count:
#     threading.Timer(5+rel, thread_run).start()
#     rel = rel + 5
#     count = count - 1

#######################################################

# import chart_studio.plotly as py
# import plotly.graph_objects as go 
# from plotly.offline import plot
# import plotly.graph_objs as go
# import chart_studio.plotly as py 
# Create your views here.

def home(request):
    video = video_content.objects.all()
    video.delete()
    # context = {
        # 'video' : video,
    # }
    # video = video_content.objects.all()
    # video.delete()

    return render(request, 'post/home.html')

def about(request):
    return render(request, 'post/about.html')

def made_by(request):
    return render(request, 'post/made_by.html')

# def video_content(request):

#     if 'image' in request.FILES:
#         video = request.FILES['image']
#     video = video_content(dummi_videos = video)
#     video.save()

#     return redirect('post:home')
def insert_video(request):
    video_delete = video_content.objects.all()
    video_delete.delete()

    input_video = request.FILES['input_video_1']
    str_input_video = str(input_video)
    str_input_video = str_input_video.split('.')[0]
    video = video_content(video = input_video, title=str_input_video)
    video.save()

    # print(video)
    script_mat = '_C'
    mat_name = str_input_video.split('.')[0]

    mat_check = mat.objects.all()


    
    # print(mat_score)
    video = video_content.objects.all()
    url = "../media/post/"
    video_path = url + str(input_video)
    print(video_path)

    context = {}
    context['video'] = video[0]



    return render(request, 'post/inserted.html', context)


def home_number(request):
    if 'non_member_login' in request.POST.keys():
        video = video_content.objects.all()
        video.delete()

        return render(request, 'post/home2.html')
    
    else:
        return render(request, 'post/error.html')

def main(request):
    return render(request, 'post/home2.html')

def error(request):

    return render(request, 'post/error.html')

def about2(request):
    return render(request, 'post/about2.html')

def about3(request):
    return render(request, 'post/about3.html')


def home_video(request):
    video = video_content.objects.all()
    video.delete()


    return render(request, 'post/home2.html')


def result(request):
    video = video_content.objects.all()

    isnormal = "normal"
    script = '_C'
    mat_name = video[0].title 
    print(str(mat_name))
    str_mat_name = str(mat_name)

    getmat = mat.objects.get(title = str_mat_name + ".mat")
    load_mat = loadmat(getmat.mat)
    mat_score = load_mat['predictions']
    format_score = []
    format_score_str = {}
    count = 1
    for i in mat_score:
        
        formatting = format(i[0], '.4f')
        float_formatting = float(formatting)
        count_to_dic = str(count) + "/32"
        if float_formatting > 0.4:
            format_score_str[count] = count_to_dic+ " " + formatting + " abnormal"
        else:
            pass

        format_score.append(float_formatting)
        count = count + 1

    # 12개

    if len(format_score_str.values()) > 3:
        isnormal = "abnormal"
    else:
        pass

###### plt ########
##### matplot #####
    # plt.plot(range(10))
    # fig = plt.gcf()
    # buf = io.BytesIO()
    # fig.savefig(buf, format='png')
    # buf.seek(0)
    # string = base64.b64encode(buf.read())
    # url = urllib.parse.quote(string)

    # context['data'] = url
    # data2 = np.linspace(1, len(data1), 32)
    # data3 = pd.DataFrame(data1, data2)

    # plt.plot(data3)
    # plt.savefig()

    plt.figure(figsize=(5.1,2.2))
    plt.plot(np.linspace(1, 32, 32), format_score, c='r', label="abnormal_score")
    plt.plot(np.linspace(1, 32, 32), [0.4 for x in range(32)], 'b--')
    plt.yticks(np.linspace(0, 1, 11))
    plt.xticks(np.linspace(0, 32, 9))
    plt.legend()

    fig = plt.gcf()
    buf = io.BytesIO()
    fig.savefig(buf, format='png')
    buf.seek(0)
    string = base64.b64encode(buf.read())
    uri = urllib.parse.quote(string)

#####################

    context = { 'video' : video[0],
                'isnormal' : isnormal,
                'format_score_str' : format_score_str.values(),
                'data' : uri
    }
    return render(request, 'post/result.html', context)

web/yonomAIproject/post/templates/post/about.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{%static 'post/about2.css' %}" type="text/css"/>
{% endblock %}

{% block content%}
    <h2>[yOnOm CCTV Detection 동작 원리]</h2>
    <br>
    <section id='c3d_explain'>
        <img id='c3d_img' src="{%static 'post/image/howtoc3d.jpg' %}" alt="c3d_원리" width="400" height="200">
        <br></br>
        </br>
        <div id='c3d_text' style='text-align:left'>
            C3D의 feature extraction 기능을 이용하고자 각 영상(mp4)에서 </br>16프레임단위로 fc6-1데이터를 생성합니다.
            </br>만들어진 데이터를 평균 내고, 정규화 하여 각 영상의 C3D feature를 추출합니다.</br></br>
        </div>
    <a href="{%url 'post:about2'%}">next
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-right-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-11.5.5a.5.5 0 0 1 0-1h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5z"/>
    </svg>
    </a>



    </section>
{% endblock%}

web/yonomAIproject/post/templates/post/about2.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{%static 'post/about2.css' %}" type="text/css"/>
{% endblock %}

{% block content%}

    <section id='model_explain'>
        </br>
        <img id='model_img' src="{%static 'post/image/howtowork.jpg' %}" alt="모델_원리" width="600" height="200">
        <br></br>
        <div id='model_text' style='text-align:left'>
            위 C3D와 segment 변환을 거쳐 영상을 전처리해 feature를 추출합니다.<br>
            추출된 (1,4096)의 feature를 모델에 넣어 각 bag instance의 이상행동 score를 정합니다.<br>
            </br>
            positive bag과 negative bag 안의 가장 높은 score를 가진 instance를 비교하여, </br>positive bag instance의 score가 더 크다면 올바른 판단,<br>
            negative bag instance의 score가 더 크다면 틀린 판단이라고 정의합니다</br>이를 손실함수에 적용하고 반복적으로 학습하여 loss를 줄입니다.<br></br>
            위 모델은 이상행동의 기준이 주관적이기 때문에 어려웠던 기존의 분류 문제를 </br>재귀적인 방법으로 해결하고 높은 수준의 성능을 보입니다.
        </div>
        <br></br>
    </section>
    <div href="tab_href">
        <a href="{%url 'post:about'%}">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-left-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5.5a.5.5 0 0 0 0-1H5.707l2.147-2.146a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708-.708L5.707 8.5H11.5z"/>
        </svg>
        before
        </a> 
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{%url 'post:about3'%}">
        next
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-right-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-11.5.5a.5.5 0 0 1 0-1h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5z"/>
        </svg>
        </a>
    </div>
{% endblock%}

web/yonomAIproject/post/templates/post/about3.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
{% endblock %}
{% block content%}
    <section id='ref'>
    <h2>참고 문헌 목록</h2>
    </br>
    <a href="https://openaccess.thecvf.com/content_cvpr_2018/papers/Sultani_Real-World_Anomaly_Detection_CVPR_2018_paper.pdf">
    - Real-world Anomaly Detection in Surveillance Videos(2018)</a>
    </br>
    <a href="https://github.com/dolongbien/HumanBehaviorBKU">
    - https://github.com/dolongbien/HumanBehaviorBKU</a>
    <br>
    <a href="https://github.com/WaqasSultani/AnomalyDetectionCVPR2018">
    - https://github.com/WaqasSultani/AnomalyDetectionCVPR2018</a>
    </section>
    </br>
    <section id='ref'>
    <h2>데이터셋 출처</h2>
    </br>
    </a href="https://aihub.or.kr/aidata/139/tool">
    - https://aihub.or.kr/aidata/139/tool</a>
    </br>
    </a href="https://www.crcv.ucf.edu/projects/real-world/">
    - UCF-Crime Dataset</a>
    </section>
    </br>
    <a href="{%url 'post:about2'%}">
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-left-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5.5a.5.5 0 0 0 0-1H5.707l2.147-2.146a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708-.708L5.707 8.5H11.5z"/>
    </svg>
    before
    </a> 
{% endblock%}

web/yonomAIproject/post/templates/post/error.html
{% extends 'base.html' %}

{% block style %}
{% endblock %}

{% block content %}
<h1>서비스 준비중입니다!!</h1>
</br>
</br>
<h4><a href = "{% url 'post:home' %}">돌아가기ㅎㅎ</a></h4>
{%endblock%}

web/yonomAIproject/post/templates/post/home.html
{% comment %} {% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{%static 'post/home.css' %}" type="text/css"/>
{% endblock %}



{% block content %}
<div class='main_home_container'>

  <form action="{%url 'post:home_number'%}" method='POST'>
  {% csrf_token %}
  </br></br></br></br></br></br></br></br>
  <div class="form-group">
    <label for="exampleInputEmail1">check your email</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <small id="emailHelp" class="form-text text-muted">If you don't have an ID, please click non-member login </small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">check your password</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="form-group form-check">

  </div>
  <button type="submit" class="btn_btn-primary" name="member_login">member login</button>
    <button type="submit" class="btn_btn-primary" name="non_member_login">non-member login</button>
  </form>
</div>
{%endblock%}

 {% endcomment %}

{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v4.1.1">
  <title>yOnOm AI project</title>

  <link rel="stylesheet" href="{%static 'post/home.css'%}" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
  <div class='main_home1_container'>
    <div class='main_home_content'>

      <div class='main_header'>
        <div class="yonom">yOnOm</div>
        <div class="cctvabnormal">CCTV Abnormal Behavior Detection</div>
        <button type="submit" class="btn_btn-primary2" name="sign_up">Sign Up</button>
      </div>
      

      <form action="{%url 'post:home_number'%}" method='POST' class='main_form'>
      {% csrf_token %}
        <div class="form-group1">
          <label class='label1'>로그인</label>
          <input type="text" class="form-control1" placeholder='Your Email'/>
          {% comment %} <label class='label1'>Password</label> {% endcomment %}
          <input type="password" class="form-control1" placeholder='Password'/>
          {% comment %} <small>If you don't have an ID, please click non-member login</small></br> {% endcomment %}
          
          <button type="submit" class="btn_btn-primary1" name="member_login">Sign In</button>
          {% comment %} <input type="checkbox" id="ex_chk">
          <label for="ex_chk">로그인 상태 유지</label> {% endcomment %}
          {% comment %} <small>아이디/비밀번호 찾기</small></br> {% endcomment %}
          <a href="" class='findID'>이메일 / 비밀번호 찾기</a>
          <hr align=left width=100% color='whitesmoke'>
          <button type="submit" class="btn_btn-primary1" name="non_member_login">Non-member Sign In</button>
          
        </div>
      </form>

    </div>
  </div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

web/yonomAIproject/post/templates/post/home2.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{%static 'post/home2.css' %}" type="text/css" />


{% endblock %}

{% block content %}
    <div class="home2_container">
        <div class="home2_content1">
            <div class="home2_video">
                <div class="home2_video_1"> 
                    <video name='demo' controls autoplay width='100%' height='100%'><source src="../media/{{video.video}}" type="video/mp4"></source></video>
                </div>
            </div>
            <div class="home2_event">
                <div class="home2_log_event">
                </div>
                <div class="home2_result_event"></div>
            </div>
        
        </div>
        <div class="home2_content2">

            <form action = "{% url 'post:insert_video' %}" method="POST" enctype="multipart/form-data" class="content2_video" >
            {% csrf_token %}
            <div class="home2_content2_1">
                <input type='file' class='input_video_1' name='input_video_1' />
            </div>
            <div class="home2_content2_2">
                <div class="home2_content2_2_video_button"><button type="submit">확인</button></div>
            </div>
            </form>

        </div>
    </div>
{% endblock%}

web/yonomAIproject/post/templates/post/home3.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{%static 'post/home3.css' %}" type="text/css" />
{% endblock %}

{% block content %}

    <div class="home3_container">
        <div class="home3_content1">
            <div class="home3_video">
                <div class="home3_video_1">
                    <video name='demo' controls autoplay width='100%' height='100%'><source src="../media/{{video1.video}}" type="video/mp4"></source></video>
                </div>
                <div class="home3_video_2">
                    <video name='demo' controls autoplay width='100%' height='100%'><source src="../media/{{video2.video}}" type="video/mp4"></source></video>
                </div>
                <div class="home3_video_3">
                    <video name='demo' controls autoplay width='100%' height='100%'><source src="../media/{{video3.video}}" type="video/mp4"></source></video>
                </div>
            </div>
            <div class="home3_event">
                <div class="home3_log_event"> event log</div>
                <div class="home3_result_event"> event result</div>
            </div>
        
        </div>
        <div class="home3_content2">
            <form action = "{% url 'post:insert_video' %}" method="POST" enctype="multipart/form-data" class="content3_video" >
            {% csrf_token %}  

            <div class="home3_content2_1">
                <input type='file' class='input_video_1' name='input_video_1' />
                <input type='file' class='input_video_2' name='input_video_2' />
                <input type='file' class='input_video_3' name='input_video_3' />
            </div>

            <div class="home3_content2_2">
                <div class="home3_content2_2_video_num"><input type="text" name="number" value="{{number}}" size=2/></div>
                <div class="home3_content2_2_video_button"><button type="submit">확인</button></div>
            </div>
            </form>

        </div>
    </div>


{% endblock%}

web/yonomAIproject/post/templates/post/home4.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{%static 'post/home4.css' %}" type="text/css" />
{% endblock %}

{% block content %}
    <div class="home4_container">
        <div class="home4_content1">
            <div class="home4_video">
                <div class="home4_video_12">
                    <div class="home4_video_1">
                        <video name='demo' controls autoplay width='100%' height='100%'><source src="../media/{{video1.video}}" type="video/mp4"></source></video>
                    </div>
                    <div class="home4_video_2">
                        <video name='demo' controls autoplay width='100%' height='100%'><source src="../media/{{video2.video}}" type="video/mp4"></source></video>
                    </div>
                </div>

                <div class="home4_video_34">
                    <div class="home4_video_3">
                        <video name='demo' controls autoplay width='100%' height='100%'><source src="../media/{{video3.video}}" type="video/mp4"></source></video>
                    </div>
                    <div class="home4_video_4">
                        <video name='demo' controls autoplay width='100%' height='100%'><source src="../media/{{video4.video}}" type="video/mp4"></source></video>
                    </div>
                </div>
            </div>
            <div class="home4_event">
                <div class="home4_log_event"> event log</div>
                <div class="home4_result_event"> event result</div>
            </div>
        
        </div>
        
        <div class="home4_content2">
            <form action = "{% url 'post:insert_video' %}" method="POST" enctype="multipart/form-data" class="content4_video" >
            {% csrf_token %}  
                <div class = "home4_content2_1">
                    <input type='file' class='input_video_1' name='input_video_1' />
                    <input type='file' class='input_video_2' name='input_video_2' />
                    <input type='file' class='input_video_3' name='input_video_3' />
                    <input type='file' class='input_video_4' name='input_video_4' />
                </div>
                <div class = "home4_content2_2">
                <div class="home4_content2_2_video_num"><input type="text" name="number" value="{{number}}" size=2/></div>
                <div class="home4_content2_2_video_button"><button type="submit">확인</button></div>
                </div>
        </form>
        
        </div>
    </div>

{% endblock%}

web/yonomAIproject/post/templates/post/inserted.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{%static 'post/home2.css' %}" type="text/css" />


{% endblock %}

{% block content %}
    <div class="home2_container">
        <div class="home2_content1">
            <div class="home2_video">
                <div class="home2_video_1"> 
                    <video name='demo' controls autoplay width='100%' height='100%'><source src="../media/{{video.video}}" type="video/mp4"></source></video>
                </div>
            </div>
            <div class="home2_event">
                <div class="home2_log_event">
                </div>
                <div class="home2_result_event"></div>
            </div>
        
        </div>
        <div class="home2_content2">

            <form action = "{% url 'post:result' %}" method="POST" enctype="multipart/form-data" class="content2_video" >
            {% csrf_token %}
            <div class="home2_content2_1">
                <h4>{{video.title}}</h4>
            </div>
            <div class="home2_content2_2">
                <div class="home2_content2_2_video_button"><button type="submit">결과확인</button></div>
            </div>
            </form>

        </div>
    </div>
{% endblock%}

web/yonomAIproject/post/templates/post/made_by.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{%static 'post/made_by.css' %}" type="text/css" />

{% endblock %}

{% block content %}
<div class='made_by_container'>
    <div class="team_name">
    {% comment %} <h1>yOnOm Team Member</span> {% endcomment %}
    <path fill-rule="evenodd" d="M8 11a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5zm0 1a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
    <path d="M3 6.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
    </svg>
    </h1>
    </div>
    <div class="team_info">
        </br>
        </br>
        </br>
        <span id='total'>
            <span id='team_intro1'>
                <section id='강'>
                    <img id='강_img' src="../../static/post/image/mj.jpg" alt="김" width="150" height="150">
                    <br></br>
                    <div id='강_text'>
                        강민지</br>
                        email : 5622kmj@likelion.org<br>
                        담당 : 데이터 전처리, 모델링
                    </div>
                    <br></br>
                </section>
                <section id='김'>
                    <img id='김_img' src="../../static/post/image/ch.jpg" alt="김" width="150" height="150">
                    <br></br>
                    <div id='김_text'>
                        김채현</br>
                        email : 9808gus@likelion.org<br>
                        담당 : 데이터 전처리, 모델링, 웹 구현
                    </div>
                    <br></br>
                </section>
            </span>
            <span id='team_intro2'>
                <section id='배'>
                    <img id='김_img' src="../../static/post/image/sb.jpg" alt="김" width="150" height="150">
                    <br></br>
                    <div id='배_text'>
                        배성빈</br>
                        email : seongbin5962@likelion.org<br>
                        담당 : 데이터 전처리, 모델링, 웹 구현<br>
                    </div>
                    <br></br>
                </section>
                <section id='최'>
                    <img id='김_img' src="../../static/post/image/sy.jpg" alt="김" width="150" height="150">
                    <br></br>
                    <div id='최_text'>
                        최서윤</br>
                        email : ab3492@likelion.org<br>
                        담당 : 데이터 전처리, 모델링, 웹 구현
                    </div>
                    <br></br>
                </section>
            </span>
        </span>
    </div>
</div>
{% endblock%}

web/yonomAIproject/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>yOnOm AI project</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/cover/">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- Bootstrap core CSS -->
{% comment %} <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet"> {% endcomment %}

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'cover.css'%}" rel="stylesheet">
    {% block style %}
    {% endblock %}
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <a href="{% url 'post:home'%}"><h3 class="masthead-brand">yOnOm</h3></a>
      <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link active" href="{% url 'post:home_video'%}">Main</a>
        <a class="nav-link active" href="{% url 'post:about' %}">About</a>
        <a class="nav-link active" href="{% url 'post:made_by' %}">Made_by</a>
      </nav>
    </div>
  {% comment %} </div> {% endcomment %}
  </header>
  {%block content%}
  {%endblock%}
  <footer class="mastfoot mt-auto">
    <div class="inner">
      {% comment %} <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p> {% endcomment %}
    </div>
  </footer>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
</html>